name: Docker Execution
on:
  push:
  workflow_dispatch:

jobs:
  linuxjob:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: badri.vaikunth@gmail.com
        password: ${{ secrets.dockerpassword }}
    - name: Docker Info
      run: docker info
    - name: Docker HelloWorld
      run: docker run hello-world

  WindowsJob:
    runs-on: windows-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: badri.vaikunth@gmail.com
        password: ${{ vars.dockerpassword }}
    - name: Docker Info
      run: docker info
    - name: Docker HelloWorld
      run: docker run hello-world
